
apiVersion: apps/v1
kind: Deployment
metadata:
  #the Deployment Name
  name: demo-react-app
spec:
  #the Number of Pods
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      # Container Details
      containers:
      - name: react-app
        # Docker Image
        image: 532806123370.dkr.ecr.us-east-1.amazonaws.com/react-app-ecr-repo
        imagePullPolicy: Always
#         resources:
#          #cpu and memory limit
#           limits:
#             memory: "550Mi"
#             cpu: "500m"
        ports:
        #the port on which the app can be reached out inside the container
        - containerPort: 3000

---
#access the app in outer world with the help of load balancer
#service 
apiVersion: v1
kind: Service
metadata:
   #the Serivce Name- it should match with the lable name of the deployment 
  name: demo-react-app
spec:
  #type of the service
#   type: NodePort
#   selector:
#     app: demo-react-app
  ports:
  - name: http
  - port: 80
    targetPort: 3000
    protocol: TCP
#     nodePort: 31000
  type: LoadBalancer
  selector:
    app: react-app
